targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/core/auth/app_user.dart
          - lib/core/network/*.dart
          - lib/features/**/domain/*.dart
          - lib/features/**/models/*.dart
          - lib/features/**/presentation/controller/*.dart
      json_serializable:
        generate_for:
          - lib/core/auth/app_user.dart
          - lib/core/network/*.dart
          - lib/features/**/domain/*.dart
          - lib/features/**/models/*.dart
        options:
          field_rename: snake
