// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform => android;

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWOKeDtprwaTVG56GtEjG7mB5qZnklPLY',
    appId: '1:570284869199:android:6f7045f814850b2a130c3a',
    messagingSenderId: '570284869199',
    projectId: 'parikesit-fef3a',
    storageBucket: 'parikesit-fef3a.firebasestorage.app',
  );
}
